# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41bbd9ada127c211dce86f0dfa0f47a5cf2264e47269b0b05fd36498036103bea7906df3f28b301002816c1999a011e616375ae84c455488bd40ab6f34ab64bc

test:
  secret_key_base: 5959eb4f529f82543a34dcd406afe49efe3ac8ac1756ed693938740d9e2475129f12c5502dc07099450f106dfeefc7bc87804ce18de8a877a84764c4c57f9fcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
